baseURL = "https://www.budiyanto.com/"
theme = "LoveIt"

languageCode = "en-us"
languageName = "English"
hasCJKLanguage = false
title = "Budi Yanto"
enableGitInfo = true

# Menu config
[menu]
    [[menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
    [[menu.main]]
        weight = 2
        identifier = "til"
        pre = ""
        post = ""
        name = "TIL"
        url = "/til/"
        title = ""
    [[menu.main]]
        weight = 3
        identifier = "about"
        pre = ""
        post = ""
        name = "About"
        url = "/about/"
        title = ""
    [[menu.main]]
        weight = 4
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
        post = ""
        name = ""
        url = "https://github.com/byanto"
        title = "GitHub"

[params]
    defaultTheme = "light"
    themeAutoDetect = false
    gitRepo = "https://github.com/byanto"
    title = "Budi Yanto - Java Backend Developer | Spring Boot | TU Berlin Graduate"
    description = "Software Engineer and Java Backend Developer with a Master's degree from TU Berlin."

    # Author config
    [params.author]
        name = "Budi Yanto"
        email = ""
        link = ""

    # Header config
    [params.header]
        # Header title config
        [params.header.title]
            name = "Home"

    # Footer config
    [params.footer]
        enable = true
        hugo = true
        copyright = true
        author = true
        since = 2025
    
    # Search config
    [params.search]
        enable = true
        type = "algolia"        
        placeholder = ""        

    # Home page config
    [params.home]
        [params.home.profile]
            enable = true
            avatarURL = "/images/avatar.png"
            title = ""
            subtitle = "Software Engineer"
            typeit = true
            social = true
        [params.home.posts]
            enable = false
    
    # Social config in home page
    [params.social]
        github = "byanto"
        linkedin = "byanto"
        email = "hello@budiyanto.com"
        
